version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./nginx/certs/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - auth-service
      - player-service
      - match-service
      - tournament-service
      - admin-service
      - email-service
      - frontend

  auth-service:
    build:
      context: ./auth-service
    image: "${DOCKER_USERNAME}/auth-service:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    expose:
      - "8080"

  player-service:
    build:
      context: ./player-service
    image: "${DOCKER_USERNAME}/player-service:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    expose:
      - "8081"

  match-service:
    build:
      context: ./match-service
    image: "${DOCKER_USERNAME}/match-service:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    expose:
      - "8082"

  tournament-service:
    build:
      context: ./tournament-service
    image: "${DOCKER_USERNAME}/tournament-service:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    expose:
      - "8083"

  admin-service:
    build:
      context: ./admin-service
    image: "${DOCKER_USERNAME}/admin-service:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    expose:
      - "8084"

  email-service:
    build:
      context: ./email-service
    image: "${DOCKER_USERNAME}/email-service:latest"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      - .env
    expose:
      - "8085"

  frontend:
    build:
      context: ./frontend
    image: "${DOCKER_USERNAME}/frontend:latest"
    expose:
      - "3000"
