
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/auth-service:latest"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      ./.env

  player-service:
    build:
      context: ./player-service
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/player-service:latest"
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      ./.env

  match-service:
    build:
      context: ./match-service
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/match-service:latest"
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      ./.env

  tournament-service:
    build:
      context: ./tournament-service
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/tournament-service:latest"
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      ./.env

  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/admin-service:latest"
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      ./.env

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/email-service:latest"
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    env_file:
      ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "${DOCKER_USERNAME}/frontend:latest"
    ports:
      - "3000:3000"
