services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    env_file:
      ./.env

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
     - "8081:8081"
    env_file:
      ./.env

  match-service:
    build:
      context: ./match-service
      dockerfile: Dockerfile
    ports:
     - "8082:8082"
    env_file:
      ./.env

  tournament-service:
    build:
      context: ./tournament-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      ./.env

  matchmaking-service:
    build:
      context: ./matchmaking-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      ./.env

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    ports:
     - "8085:8085"
    env_file:
      ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - "3000:3000"